.common_setup: &common_setup
  - cd backend/cdk
  - npm i
  - npm i -g aws-cdk typescript ts-node
  # - aws sts get-caller-identity

cache:
  paths:
    - backend/apis/node_modules/

stages:
  - test
  - build
  - deploy

.install_aws: &install_aws
  - apt update
  - apt install -y jq
  - curl -k "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip "awscliv2.zip"
  - ./aws/install

.common_install: &common_install
  - cd backend/apis
  - npm i

.assume_role: &assume_role
  - >
    export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
    $(aws sts assume-role-with-web-identity
    --role-arn ${ROLE_ARN}
    --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
    --web-identity-token ${GITLAB_OIDC_TOKEN}
    --duration-seconds 3600
    --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
    --output text))
  - aws sts get-caller-identity

test_lambda:
  stage: test
  image: node:20.11.1
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - changes:
      - backend/apis/**/*
  script:
    - *common_install
    - npm run test

build_staging:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "staging"'
      changes:
        - backend/apis/**/*
  artifacts:
    expose_as: 'backend-build-staging'
    name: 'backend-build-staging'
    paths:
      - $PWD/backend/apis/.serverless/jngpaypal.zip
  needs:
    - job: test_lambda
  dependencies:
    - test_lambda
  environment:
    name: staging
  script:
    - *common_install
    - touch .env
    - |
      variables=(
        "ORIGIN=${ORIGIN}"
        "SEND_GRID_API_KEY=${SEND_GRID_API_KEY}"
        "ACCESS_KEY_ID=${ACCESS_KEY_ID}"
        "SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}"
        "WHICH_ROUTE=${WHICH_ROUTE}"
        "NODE_ENV=staging"
      )
      env_file="./.env"
      for var in "${variables[@]}"; do
        echo "$var" >> "$env_file"
      done
    - npm run package

deploy_staging:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  stage: deploy
  environment:
    name: staging
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "staging"'
      changes:
        - backend/apis/**/*
  needs:
    - job: build_staging
      artifacts: true
  dependencies:
    - build_staging
  script:
    - *install_aws
    - *common_setup
    - *assume_role
    - npm i
    - |
      variables=(
        "ACCESS_KEY_ID=${ACCESS_KEY_ID}"
        "CALENDLY_API_ACCESS_TOKEN=${CALENDLY_API_ACCESS_TOKEN}"
        "DEAD_LETTER_QUEUE_URL=${DEAD_LETTER_QUEUE_URL}"
        "NODE_ENV=staging"
        "ORIGIN=${ORIGIN}"
        "SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}"
        "SEND_GRID_API_KEY=${SEND_GRID_API_KEY}"
        "STAGE=prod"
        "WHICH_ROUTE=${WHICH_ROUTE}"
      )
      env_file="./.env"
      for var in "${variables[@]}"; do
        echo "$var" >> "$env_file"
      done
    - cdk deploy --require-approval=never --role-arn ${INFRASTRUCTURE_ROLE_ARN}

build_production:
  artifacts:
    expose_as: 'backend-build-production'
    name: 'backend-build-production'
    paths:
      - $PWD/backend/apis/.serverless/jngpaypal.zip
  needs: ['test_lambda']
  dependencies:
    - test_lambda
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - backend/apis/**/*
  stage: build
  environment:
    name: production
  script:
    - *common_install
    - touch .env
    - |
      variables=(
        "ORIGIN=${ORIGIN}"
        "SEND_GRID_API_KEY=${SEND_GRID_API_KEY}"
        "ACCESS_KEY_ID=${ACCESS_KEY_ID}"
        "SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}"
        "WHICH_ROUTE=${WHICH_ROUTE}"
        "NODE_ENV=production"
        "STAGE=prod"
      )
      env_file="./.env"
      for var in "${variables[@]}"; do
        echo "$var" >> "$env_file"
      done
    - npm run package

deploy_production:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  stage: deploy
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - backend/apis/**/*
  needs:
    - job: build_production
      artifacts: true
  dependencies:
    - build_production
  script:
    - *install_aws
    - *common_setup
    - *assume_role
    - npm i
    - |
      variables=(
        "ACCESS_KEY_ID=${ACCESS_KEY_ID}"
        "CALENDLY_API_ACCESS_TOKEN=${CALENDLY_API_ACCESS_TOKEN}"
        "DEAD_LETTER_QUEUE_URL=${DEAD_LETTER_QUEUE_URL}"
        "NODE_ENV=production"
        "ORIGIN=${ORIGIN}"
        "SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}"
        "SEND_GRID_API_KEY=${SEND_GRID_API_KEY}"
        "STAGE=prod"
        "WHICH_ROUTE=${WHICH_ROUTE}"
      )
      env_file="./.env"
      for var in "${variables[@]}"; do
        echo "$var" >> "$env_file"
      done
    - cdk deploy --require-approval=never --role-arn ${INFRASTRUCTURE_ROLE_ARN}

