export const articles: Article[] = [
  {
    title: 'Exploring Functions as Microservices: A Powerful Approach...',
    imageUrl: 'exprapidbackend',
    lengthInMinutes: 3,
    publishedDate: 'Jun 11, 2023',
    articleUrl: '/articles/rapidbackend',
    noTarget: true,
  },
  {
    title: 'Do I really need a CKA certification?',
    imageUrl: 'expcka',
    lengthInMinutes: 4,
    publishedDate: 'Jun 5, 2023',
    articleUrl: '/articles/do-i-need-a-cka',
    noTarget: false,
  },
  {
    title: 'AWS IAM — Quick Dive/Quick Guide',
    imageUrl: 'awsiam',
    lengthInMinutes: 6,
    publishedDate: 'May 28, 2023',
    articleUrl: '/articles/i-am',
    noTarget: false,
  },
  {
    title: "Are JavaScript's default parameters slowing me down?",
    imageUrl: 'dontpanic',
    lengthInMinutes: 3,
    publishedDate: 'Nov 27, 2020',
    articleUrl: '/articles/default-parameters',
    noTarget: false,
  },
  {
    title: "JavaScript's New Sexy",
    imageUrl: 'jsnew',
    lengthInMinutes: 5,
    publishedDate: 'Aug 30, 2020',
    articleUrl: '/articles/js-new-sexy',
    noTarget: false,
  },
  {
    title: 'Explain Servers to a 5 Year Old',
    imageUrl: 'explservers',
    lengthInMinutes: 3,
    publishedDate: 'Jul 25, 2020',
    articleUrl: '/articles/explain-servers-to-5-year-old',
    noTarget: false,
  },
  {
    title: 'Deploy GoLambda With MongoDB and AWS SAM (Part 3)',
    imageUrl: 'samgolambda',
    lengthInMinutes: 11,
    publishedDate: 'Dec 29, 2019',
    articleUrl: '/articles/sam-lambda-mongodb',
    noTarget: false,
  },
  {
    title: 'XML, read, send, write: Javascript front to Express/Node.js back',
    imageUrl: 'xml',
    lengthInMinutes: 4,
    publishedDate: 'Sep 2, 2019',
    articleUrl: '/articles/read-write-send-xml',
    noTarget: false,
  },
  {
    title: 'Micro Services Part II: AWS EC2 Linux AMIs',
    imageUrl: 'mspt2',
    lengthInMinutes: 4,
    publishedDate: 'Mar 16, 2019',
    articleUrl: '/articles/microservices-part-2',
    noTarget: false,
  },
  {
    title: 'Micro Services Part I: Node, Docker, and Docker Compose',
    imageUrl: 'mspt1',
    lengthInMinutes: 5,
    publishedDate: 'Mar 9, 2019',
    articleUrl: '/articles/microservices-part-1',
    noTarget: false,
  },
  {
    title: 'React Context-Api and Lazy-loading',
    imageUrl: 'reactcontext',
    lengthInMinutes: 6,
    publishedDate: 'Dec 26, 2018',
    articleUrl: '/articles/react-context-api',
    noTarget: false,
  },
];
